name: siren2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py
  - attrs
  - bleach
  - cffi
  - click
  - dask-core
  - ffmpeg
  - h5py
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scipy
  - tensorflow
  - torchvision
  - pip
  - pip:
      - astor
      - cmapy
      - gast
      - google-pasta
      - imageio-ffmpeg
      - imbalanced-learn
      - keras-applications
      - keras-preprocessing
      - moviepy
      - opencv-python
      - opt-einsum
      - proglog
      - pytz
      - tensorboard
      - tensorflow-estimator
      - termcolor
      - wrapt
      - youtube-dl

